# Generated by Django 5.0 on 2023-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_age', models.IntegerField()),
                ('student_class', models.IntegerField()),
                ('student_division', models.CharField(max_length=10)),
            ],
        ),
    ]
